config/routes.rb
BibleService::Application.routes.draw do

  resources :books do
    resources :chapters do
      resources :verses
    end
  end

  root :to => "books#index"

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many  :chapters
  
  #validates :link, :uniqueness => { :case_sensitive => false }

  validates_presence_of :name#, :link

  attr_accessible :name, :link

  def as_json(options={})
  { 
  	:name => self.name,
  	:chapters => self.chapters
  }
	end
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  belongs_to :book
  has_many :verses
  attr_accessible :number, :link
  #validates :link, :uniqueness => { :case_sensitive => false }
  
  validates_presence_of :number#, :link

  def as_json(options={})
  { 
  	:number => self.number,
  	:verses => self.verses
  }
	end
end

app/models/verse.rb
class Verse < ActiveRecord::Base
  belongs_to :chapter
  has_one :book, :through => :chapter
  attr_accessible :content, :number

  validates_presence_of :number
  validates_presence_of :content

  def as_json(options={})
  { 
  	:number => self.number,
  	:content => self.content
  }
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # GET /books
  # GET /books.json
  def index
    @books = Book.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
   before_filter :load_book

  # GET /chapters
  # GET /chapters.json
  def index
    @chapters = @book.chapters

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @chapters }
    end
  end

  # GET /chapters/1
  # GET /chapters/1.json
  def show
    @chapter = Chapter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @chapter }
    end
  end


  protected
  def load_book
    @book = Book.find(params[:book_id])
  end
end

app/controllers/verses_controller.rb
class VersesController < ApplicationController

  before_filter :load_book_and_chapter

  # GET /verses
  # GET /verses.json
  def index
    @verses = @chapter.verses

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @verses }
    end
  end

  # GET /verses/1
  # GET /verses/1.json
  def show
    @verse = Verse.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @verse }
    end
  end

  protected
  def load_book_and_chapter
    @book = Book.find(params[:book_id])
    @chapter = @book.chapters.find(params[:chapter_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/verses_helper.rb
module VersesHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/index.html.erb
<h1>Listing books</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Link</th>
    <th></th>
  </tr>

<% @books.each do |book| %>
  <tr>
    <td><%= book.name %></td>
    <td><%= book.link %></td>
    <td><%= link_to 'Show', book_chapters_path(book) %></td>
  </tr>
<% end %>
</table>

<br />

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @book.name %>
</p>

<p>
  <b>Link:</b>
  <%= @book.link %>
</p>

app/views/chapters/_form.html.erb
<%= form_for(@chapter) do |f| %>
  <% if @chapter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chapter.errors.count, "error") %> prohibited this chapter from being saved:</h2>

      <ul>
      <% @chapter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br />
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :book %><br />
    <%= f.text_field :book %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chapters/index.html.erb
<h1>Listing chapters</h1>

<table>
  <tr>
    <th>Number</th>
    <th></th>
  </tr>

<% @chapters.each do |chapter| %>
  <tr>
    <td><%= chapter.number %></td>
    <td><%= link_to 'Show', book_chapter_verses_path(chapter.book, chapter) %></td>
  </tr>
<% end %>
</table>

<br />

app/views/chapters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Number:</b>
  <%= @chapter.number %>
</p>

<p>
  <b>Link:</b>
  <%= @chapter.link %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BibleService</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/verses/_form.html.erb
<%= form_for(@verse) do |f| %>
  <% if @verse.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@verse.errors.count, "error") %> prohibited this verse from being saved:</h2>

      <ul>
      <% @verse.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br />
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :chapter %><br />
    <%= f.text_field :chapter %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/verses/index.html.erb
<h1>Listing verses</h1>

<table>
  <tr>
    <th>Number</th>
    <th>Content</th>

    
  </tr>

<% @verses.each do |verse| %>
  <tr>
    <td><%= verse.number %></td>
    <td><%= verse.content %></td>
    
  </tr>
<% end %>
</table>

<br />

app/views/verses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Number:</b>
  <%= @verse.number %>
</p>

<p>
  <%= @verse.content %>
</p>